M48
; DRILL file {KiCad 6.0.0} date Fri 07 Jan 2022 19:16:10 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-07T19:16:10+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.1024
%
G90
G05
T2
X4.0482Y-2.1713
X5.001Y-2.1713
T1
X4.6909Y-3.2126G85X5.0059Y-3.2126
G05
T0
M30
